### PR TITLE
Gear script

### PR DESCRIPTION
**Pull request by ETKuppens**
Added the first version of the gear script

### CODE REVIEW

**Comment by allmiha2** [comment]
Looks good. I saw you also created the gear-objects branch with the complete versions of the folders for each component. Do you want to merge that one and close all the other branches or do you still want to modify the gear-objects branch?

**Comment by ETKuppens** [comment]
Sorry for my late reply. I wasn't sure how you setup the branches, so please do what you think is best.

**Comment by allmiha2** [comment]
Yep i will do a pull request for the gear-objects branch that you created, since, if im not mistaken, it has all the files and folders that we need for the components we have until now (N. motor, S. motor, Switch, Gears) and I'll merge it a bit later to give you a bit of time to review it

**Comment by allmiha2** [comment]
Actually @ETKuppens I just realized, could you please convert the gear objects that you have in your local unity project to prefabs and upload the prefabs into the gears folder? Because in the gears folder in the gears-objects branch, you added the objects for the gears and the script but if someone else wants to download the project from the repository, they'll have to re-assemble the object (aka to add the rigidbody component if it has any or to attach the script or any other property the gears have in your project). But if you convert them to prefabs, when someone else downloads the project, he can just drag the prefab onto the scene and it will have all the components and properties you have originally imposed. If what I'm saying is confusing or anything please let me know =)))

**Pull request closed without merging**
